### PR TITLE
submodule os path modifications and simple api

### PR DESCRIPTION
**Pull request by goldsamantha**
This is a kinda hacky bit to get submodules to work--I will update in separate commit with fix for all effects (this is only for a couple to sample on). 
I was thinking it would be good to separate this fix into a simple util function (that way if we ever get a better way to do this than using the os path, it's only a fix in one place). But I'm mostly using this PR as a way to direct your attention to the following:

https://github.com/sgoldst3/inyourface-api

Right now it's _extremely_ simple. I just want to know what you think about how it's starting and if it's easy to get it up and running. Let me know if there are things I missed and should add to the readme, etc! 

Also I don't necessarily think this PR needs to be merged yet (maybe when I've fixed it up for all the effects?)

### CODE REVIEW

**Comment by yacomink** [comment]
bitmoji

I got this working in a similar hacky way using `__file__` instead of inspect, over here: https://github.com/yacomink/inyourface/blob/run-it-on-gcp/inyourface/effect/Juggalo.py#L18-L20 and similarly only did it for a couple of effects!

Your start on the API looks great! I would consider doing the google credential and image directory configuration a little bit differently, and passing those values to your process as environment variables. There's some [good justification for that pattern in the 12 factor app](https://12factor.net/config). (That's also generally an interesting thing to skim when you're designing a new app/api/service). More practically ... it would make it easier to spin it up as a service on most cloud providers.

**Comment by goldsamantha** [comment]
Ah great! I'm going to take a look at it now and get a PR ready for ya! Do you think it's a good idea to separate this stuff out into two different repos like I have it here?
It seems like the direction we're going is: this repo for the inyourface library proper (to be come pip library <3), and maybe another one for the api/slack app--does that seem reasonable?

Thinking (kinda just malformed musings tbh) about how we could deal with the slack app needing a return object in 3s:
The file names are deterministic right? Are they seeded based on the input params? In which case could we maybe return back the name of the file, before it was properly generated and returned from the google vision api? And furthermore, would having the file name but no file yet make any difference, or would it still cause the same issues?

**Comment by yacomink** [comment]
Yeah, I think splitting the api out into a different repo is a great idea, and seeing that totally sparked the idea of just making this bit into a pip package. Also I was checking in like docker files for getting it working on GCP, and this felt like a bad place for them.

The file names _are_ deterministic, but Slack will try to unfurl them immediately, so I think you'd wind up with a broken looking image if you returned it immediately. I've been thinking about a scheme where the request from slack always just queues a message and returns null, and then there's a worker running that pulls the queued message, makes the image, and does a callback to slack.

**Comment by goldsamantha** [comment]
Boop boop! there's one thing in here i feel a bit squiggly about and that's the way I'm not using the Animator object function in the masked files since those are global vars and don't have the class's state. Anyway--i can look into that later or if you have a quick fix that's coo. Let me know what you think. As always, happy to change whatever

**Comment by yacomink** [comment]
Looking good! I think you could make get_os_dir a static method (
https://docs.python.org/2/library/functions.html#staticmethod) in Animator
and then you'd be able to call Animator.get_os_dir without having an
instance of the class

**Comment by goldsamantha** [comment]
yeee perf. Static methods appeared to me in my dream last night, like, why didn't you use this. I'll update in a bit!

**Pull request merged**
